puts "The students of Villains Academy"
puts "---------------"
puts "Dr. Hannibal Lector"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked With of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"

print "Overall, we have "
print 11
puts " great students"